// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string):Promise<void>;

export function CheckTodo(arg1:string):Promise<void>;

export function GetTodos():Promise<main.Todos>;

export function GetWindowsTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RemoveTodo(arg1:string):Promise<void>;

export function Test():Promise<string>;
