// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function CheckTodo(arg1) {
  return window['go']['main']['App']['CheckTodo'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function GetWindowsTheme() {
  return window['go']['main']['App']['GetWindowsTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveTodo(arg1) {
  return window['go']['main']['App']['RemoveTodo'](arg1);
}

export function Test() {
  return window['go']['main']['App']['Test']();
}
