// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1:string):Promise<void>;

export function GetTodos():Promise<Array<string>>;

export function GetWindowsTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RemoveTodo(arg1:string):Promise<void>;

export function Test():Promise<string>;
